version: '3.2'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=mobiusdb
    ports:
      - 3306:3306
    volumes:
      - mysql-storage:/var/lib/mysql
      - ./data/mobiusdb.sql:/docker-entrypoint-initdb.d/mobiusdb.sql
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 9001:9001
      - 1883:1883
    volumes:
      - mosquitto-storage:/mosquitto/data
  mobius:
    image: easyglobalmarket/mobius:latest
    restart: always
    ports:
      - 7579:7579
    depends_on:
      - mysql
      - mosquitto
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PWD=${MYSQL_ROOT_PASSWORD}
      - MQTT_HOST=mosquitto
    labels:
      kompose.service.expose: "true"
      kompose.service.type: nodeport
  postgres:
    image: timescale/timescaledb-postgis:latest-pg11
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=onem2m
      - POSTGRES_DB=onem2m_recorder
    ports:
      - 5432:5432
    volumes:
      - postgres-storage:/var/lib/postgresql/data
      - ./src/main/resources/db/migration/V1__init.sql:/docker-entrypoint-initdb.d/V1__init.sql
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    labels:
      kompose.service.expose: "true"
      kompose.service.type: nodeport
  onem2m-recorder:
    image: easyglobalmarket/onem2m-recorder
    restart: always
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=int"
      - APPLICATION_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - APPLICATION_ONEM2M_ORIGIN=${MOBIUS_ORIGIN}
    volumes:
      - ./logs:/app/logs

volumes:
  grafana-storage:
  mysql-storage:
  mosquitto-storage:
  postgres-storage: