apiVersion: v1
kind: Service
metadata:
  labels:
    app: etsi-iot-week-grafana
  name: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: etsi-iot-week-grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etsi-iot-week-grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: etsi-iot-week-grafana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etsi-iot-week-grafana
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        env:
        - name: GF_SERVER_ROOT_URL
          value: http://localhost:3000/grafana/
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin        
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-pv
      restartPolicy: Always
      securityContext:
        fsGroup: 472
      volumes:
      - name: grafana-pv
        persistentVolumeClaim:
          claimName: grafana-pv-claim
