apiVersion: v1
kind: Service
metadata:
  labels:
    app: etsi-iot-week
  name: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: etsi-iot-week
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: etsi-iot-week
  name: grafana-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etsi-iot-week
  name: grafana
spec:
  selector:
    matchLabels:
      app: etsi-iot-week
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etsi-iot-week
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-pv
      restartPolicy: Always
      securityContext:
        fsGroup: 472
      volumes:
      - name: grafana-pv
        persistentVolumeClaim:
          claimName: grafana-pv-claim
