apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mobius
  name: mobius
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mobius
    spec:
      containers:
      - env:
        - name: MQTT_HOST
          value: mosquitto
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PWD
        image: easyglobalmarket/mobius:latest
        name: mobius
        ports:
        - containerPort: 7579
        resources: {}
      restartPolicy: Always
status: {}
