apiVersion: v1
kind: Service
metadata:
  labels:
    app: etsi-iot-week
  name: mysql
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: etsi-iot-week
  clusterIP: None  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: etsi-iot-week
  name: mysql-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etsi-iot-week
  name: mysql
spec:
  selector:
    matchLabels:
      app: etsi-iot-week
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etsi-iot-week
    spec:
      containers:
      - image: mysql
        name: mysql
        args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: mobiusdb
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-pv
        - mountPath: /docker-entrypoint-initdb.d/mobiusdb.sql
          name: mysql-claim1
      restartPolicy: Always
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-claim1
        persistentVolumeClaim:
          claimName: mysql-claim1
