apiVersion: v1
kind: Service
metadata:
  labels:
    app: etsi-iot-week-onem2m
  name: onem2m-recorder
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: etsi-iot-week-onem2m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etsi-iot-week-onem2m
  name: onem2m-recorder
spec:
  selector:
    matchLabels:
      app: etsi-iot-week-onem2m
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etsi-iot-week-onem2m
    spec:
      containers:
      - image: easyglobalmarket/onem2m-recorder
        name: onem2m-recorder
        env:
        - name: APPLICATION_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: password
        - name: APPLICATION_ONEM2M_ORIGIN
          valueFrom:
            secretKeyRef:
              name: onem2m
              key: origin
        - name: APPLICATION_BASE_URL
          value: http://onem2m-recorder:8080
        - name: SPRING_PROFILES_ACTIVE
          value: int
        ports:
        - containerPort: 8080
      restartPolicy: Always
