apiVersion: v1
kind: Service
metadata:
  labels:
    app: etsi-iot-week
  name: postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: etsi-iot-week
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: etsi-iot-week
  name: postgres-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: cinder-high-speed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etsi-iot-week
  name: postgres
spec:
  selector:
    matchLabels:
      app: etsi-iot-week
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etsi-iot-week
    spec:
      containers:
      - image: timescale/timescaledb-postgis:latest-pg11
        name: postgres
        env:
        - name: POSTGRES_DB
          value: onem2m_recorder
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: password
        - name: POSTGRES_USER
          value: onem2m
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-pv
        - mountPath: /docker-entrypoint-initdb.d
          name: postgres-initdb
      restartPolicy: Always
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      - name: postgres-initdb
        configMap:
          name: postgres-init-db
